# Generated by cucumber-sinatra. (2015-06-11 16:50:16 -0500)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'shopping_cart.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = ShoppingCart

class ShoppingCartWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  ShoppingCartWorld.new
end
